version: '3'

services:
    bot:
        build: .
        restart: always
        command: ["node", "./index.js"]
        depends_on:
          - mysql
    mysql:
        image: mariadb:10.2.15
        env_file: .env
        restart: unless-stopped
        ports:
          - 127.0.0.1:3306:3306
        volumes:
          - "~/mysql:/var/lib/mysql"
    webhook:
        restart: unless-stopped
        image: staticfloat/docker-webhook
        volumes:
            # Mount this code into /code
            - ./:/code
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        env_file: .env
        expose:
            - 3000