version: '3'

services:
    bot:
        image: thomasvt1/memebot
        restart: always
        depends_on:
          - mysql
    mysql:
        image: mariadb:10.2.15
        env_file: .env
        restart: unless-stopped
        ports:
          - 127.0.0.1:3306:3306
        volumes:
          - "~/mysql:/var/lib/mysql"